sudo: false
dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
  - git clone --depth 1 https://github.com/igniterealtime/ci-tooling.git target/ci-tooling
  - cp target/ci-tooling/maven-settings-for-openfire-plugins.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  script: mvn deploy --settings target/ci-tooling/maven-settings-for-openfire-plugins.xml
  skip_cleanup: true
  on:
    repo: igniterealtime/openfire-fastpath-plugin
    all_branches: true
env:
  global:
  - secure: CEqHJKX24SmekDyTUquR3zAZ6/oJRc0rR+80CNzsu/YokC8KoudsQFpSZy8WzwDkZelONf3y/dfJs7FtFlHGFVHRXsBY0BH1jyE0aaUc/UA6DTFws8/IPmJJAmllq+1JyALTZ/JZLtOMfV3DcwC0tADVwKNMB0M/uia+1mw+qdNbPkoCwwrf8eJRg5as8g/6xAWiuF5/NTP3BT0+54RQiX9pbiDHZRAd3//DBTQu1z7oz7r/NRbNhRnUdSC+b9Jqd6W26WpwKPo9AykdSrFqUln5xYznAJlNXWwkN0D+b1HnZdvpVuCn0SQjePD6uZvXgN2g+3e+iM1eamFQCEOfv4ddFejHXe1l6t+goOc0AG7pXtAxPk7OxasbEJyYNZCloLGt7y/3nndonNacVpUVDNtzHi4nsTdZM18JzSHhH6lk2CAS9eMYoNRVSDHVMJvGdVkfbXxR49xLj0ZmG+vBAVZozIQkwwvR3dL4y3WgIGj89b281oaXdiJWoWxZuZIVRufAxuQvQrAT7e2FNlTPZjPymgc/3FQl04YFkZTvBivcV/o4oiyEkrR36RnKuUGxR6MCMTqQORJuTBk95r/lKanNY8F4OXD2TXlMHwU5PEMNB3XTctE5VHc1ROtLiW8wwzYILHEa2CEKqfo0RJUzBR/8Bj0Ql5KaGiykpRmjkWs=
  - secure: YdSpSLD9Sz6PlCccou0kMIJCQNfZzL3EpJnDq3B4z7pjTlRbX4RGOODCmqwW0Og16dqLZdHaE/ZZX5IZn1CIyWr990vxGcvMChRQ1nICwyhYAWmBw+3GsWqz7ESybb7jCPAtL03cJkrkvmwtwMI6CgS3AWVLsCdIeSd/3tm2FgGWccUgmCp+FVJggeLe82XWcGF55MAO41aBaIyhHRm0XA0mpZC4Elf2eZQo7VmcJKLoiscVK4qhB4RzKqRDNvp0vtglNtohZuqC5sMWQQul8vSEvas1bFfY/4b3586cukpYZi3+UbW7uAmyB1QDakdUERz+cgCJ1C5BbzTI9CBK76RjBe/3ZQGNWOlKpu+XECDSVUguxIgcDRaNynRSHtqrEsX4ozeyiJZRE8e0CL5V1mKicnT4/eWLdS+7TuCLTrq94zuZdPFSyIyrqtPreCFD347roSy1Cyv7jzs1OT5wbRPbtQbSRgSCM4lyQBrkJO0Qrs/rMVap+cgSvz0x+luKg5VrkCuJWOI07OpF++oBE/s9Awip3CSnDqQ1eM5XhQoFHwxTd0H8v3lJ2nb4oSiJ/JuH898O9e7lig87JPqrmkPNj2+BY3oCC4EUMxQCpV48ST4bHtIiPfnHmqtBr3tGWjVrCxV/W3jKVzmDdjr/HhsiMM2rz/oujQbfterjM+I=
